# Generated by Django 6.0.5 on 2026-06-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120, verbose_name="nom")),
                (
                    "nom_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="nom (EN)"
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("proteine", "Protéine"),
                            ("creatine", "Créatine"),
                            ("gainer", "Gainer (glucides + protéines)"),
                            ("acides_amines", "Acides aminés"),
                            ("pre_workout", "Pré-entraînement"),
                            ("vitamines_mineraux", "Vitamines & minéraux"),
                            ("omega3", "Oméga-3"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "benefices",
                    models.TextField(
                        blank=True,
                        help_text="Effets établis, sans promesse exagérée.",
                        verbose_name="bénéfices",
                    ),
                ),
                (
                    "dosage_recommande",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="dosage recommandé"
                    ),
                ),
                (
                    "moment_prise",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="moment de prise"
                    ),
                ),
                (
                    "niveau_preuve",
                    models.CharField(
                        choices=[
                            ("eleve", "Preuves solides"),
                            ("modere", "Preuves modérées"),
                            ("faible", "Preuves limitées"),
                        ],
                        default="modere",
                        max_length=10,
                        verbose_name="niveau de preuve",
                    ),
                ),
                (
                    "contre_indications",
                    models.TextField(blank=True, verbose_name="contre-indications"),
                ),
                (
                    "exclu_pour",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Liste de régimes incompatibles, ex: ["vegan", "vegetarien"].',
                        verbose_name="exclu pour (régimes)",
                    ),
                ),
                (
                    "priorite",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Ordre dans sa catégorie (plus petit = affiché en premier).",
                        verbose_name="priorité d'affichage",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "complément",
                "verbose_name_plural": "compléments",
                "ordering": ["categorie", "priorite", "nom"],
            },
        ),
    ]
