# Generated by Django 6.0.5 on 2026-06-14 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("H", "Homme"), ("F", "Femme")],
                        max_length=1,
                        verbose_name="sexe",
                    ),
                ),
                ("date_naissance", models.DateField(verbose_name="date de naissance")),
                (
                    "taille_cm",
                    models.PositiveSmallIntegerField(verbose_name="taille (cm)"),
                ),
                (
                    "poids_kg",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="poids (kg)"
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                        ],
                        default="debutant",
                        max_length=20,
                        verbose_name="niveau",
                    ),
                ),
                (
                    "objectif",
                    models.CharField(
                        choices=[
                            ("prise_de_masse", "Prise de masse"),
                            ("seche", "Sèche"),
                            ("recomposition", "Recomposition"),
                            ("force", "Force"),
                            ("maintien", "Maintien"),
                        ],
                        max_length=20,
                        verbose_name="objectif",
                    ),
                ),
                (
                    "activite",
                    models.CharField(
                        choices=[
                            ("sedentaire", "Sédentaire"),
                            ("leger", "Léger"),
                            ("modere", "Modéré"),
                            ("actif", "Actif"),
                            ("tres_actif", "Très actif"),
                        ],
                        default="modere",
                        max_length=20,
                        verbose_name="activité",
                    ),
                ),
                (
                    "jours_entrainement_par_semaine",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="jours d'entraînement / semaine"
                    ),
                ),
                (
                    "materiel",
                    models.CharField(
                        choices=[
                            ("salle_complete", "Salle complète"),
                            ("halteres_maison", "Haltères maison"),
                            ("poids_du_corps", "Poids du corps"),
                        ],
                        default="salle_complete",
                        max_length=20,
                        verbose_name="matériel disponible",
                    ),
                ),
                (
                    "blessures_limitations",
                    models.TextField(
                        blank=True, verbose_name="blessures / limitations"
                    ),
                ),
                (
                    "allergies_alimentaires",
                    models.TextField(blank=True, verbose_name="allergies alimentaires"),
                ),
                (
                    "preferences_alimentaires",
                    models.TextField(
                        blank=True,
                        help_text="ex: halal, végétarien, sans porc",
                        verbose_name="préférences alimentaires",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil",
                "verbose_name_plural": "profils",
            },
        ),
    ]
