# Generated by Django A.I. patch
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_site_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tutoriel_vu",
            field=models.BooleanField(default=False, verbose_name="tutoriel vu"),
        ),
    ]
