# Generated by Django 6.0.5 on 2026-06-14 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="instructions"),
                ),
                (
                    "temps_preparation_min",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="temps de préparation (min)"
                    ),
                ),
                (
                    "portions",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="portions"
                    ),
                ),
                (
                    "calories",
                    models.PositiveIntegerField(
                        verbose_name="calories / portion (kcal)"
                    ),
                ),
                (
                    "proteines_g",
                    models.PositiveSmallIntegerField(
                        verbose_name="protéines / portion (g)"
                    ),
                ),
                (
                    "glucides_g",
                    models.PositiveSmallIntegerField(
                        verbose_name="glucides / portion (g)"
                    ),
                ),
                (
                    "lipides_g",
                    models.PositiveSmallIntegerField(
                        verbose_name="lipides / portion (g)"
                    ),
                ),
                (
                    "ingredients",
                    models.JSONField(
                        blank=True, default=list, verbose_name="ingrédients"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="tags"),
                ),
                (
                    "generee_par_ia",
                    models.BooleanField(default=False, verbose_name="générée par IA"),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
            ],
            options={
                "verbose_name": "recette",
                "verbose_name_plural": "recettes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "tdee_calcule",
                    models.PositiveIntegerField(verbose_name="TDEE calculé (kcal)"),
                ),
                (
                    "calories_cibles",
                    models.PositiveIntegerField(verbose_name="calories cibles (kcal)"),
                ),
                (
                    "proteines_g",
                    models.PositiveSmallIntegerField(verbose_name="protéines (g)"),
                ),
                (
                    "glucides_g",
                    models.PositiveSmallIntegerField(verbose_name="glucides (g)"),
                ),
                (
                    "lipides_g",
                    models.PositiveSmallIntegerField(verbose_name="lipides (g)"),
                ),
                (
                    "nombre_repas",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="nombre de repas"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "plan nutritionnel",
                "verbose_name_plural": "plans nutritionnels",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="ex: petit-déj, déjeuner, collation, dîner",
                        max_length=50,
                        verbose_name="nom",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(default=1, verbose_name="ordre"),
                ),
                (
                    "calories",
                    models.PositiveIntegerField(verbose_name="calories (kcal)"),
                ),
                (
                    "proteines_g",
                    models.PositiveSmallIntegerField(verbose_name="protéines (g)"),
                ),
                (
                    "glucides_g",
                    models.PositiveSmallIntegerField(verbose_name="glucides (g)"),
                ),
                (
                    "lipides_g",
                    models.PositiveSmallIntegerField(verbose_name="lipides (g)"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="nutrition.nutritionplan",
                        verbose_name="plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "repas",
                "verbose_name_plural": "repas",
                "ordering": ["plan", "ordre"],
            },
        ),
    ]
