# Generated by Django 6.0.5 on 2026-06-14 12:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("training", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "duree_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="durée (min)"
                    ),
                ),
                (
                    "ressenti",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="ressenti (1-5)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
                (
                    "workout_day",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="training.workoutday",
                        verbose_name="journée",
                    ),
                ),
            ],
            options={
                "verbose_name": "séance réalisée",
                "verbose_name_plural": "séances réalisées",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SetLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serie_numero",
                    models.PositiveSmallIntegerField(verbose_name="numéro de série"),
                ),
                (
                    "repetitions_faites",
                    models.PositiveSmallIntegerField(verbose_name="répétitions faites"),
                ),
                (
                    "charge_kg",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="charge (kg)"
                    ),
                ),
                (
                    "rpe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="RPE",
                    ),
                ),
                (
                    "workout_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_logs",
                        to="training.workoutexercise",
                        verbose_name="exercice de séance",
                    ),
                ),
                (
                    "workout_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_logs",
                        to="tracking.workoutlog",
                        verbose_name="séance",
                    ),
                ),
            ],
            options={
                "verbose_name": "série réalisée",
                "verbose_name_plural": "séries réalisées",
                "ordering": ["workout_log", "workout_exercise", "serie_numero"],
            },
        ),
        migrations.CreateModel(
            name="BodyMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "poids_kg",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="poids (kg)"
                    ),
                ),
                (
                    "tour_taille",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="tour de taille (cm)",
                    ),
                ),
                (
                    "tour_bras",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="tour de bras (cm)",
                    ),
                ),
                (
                    "tour_poitrine",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="tour de poitrine (cm)",
                    ),
                ),
                (
                    "tour_cuisses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="tour de cuisses (cm)",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="mesures/",
                        verbose_name="photo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "mesure corporelle",
                "verbose_name_plural": "mesures corporelles",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
