# Generated by Django 6.0.5 on 2026-06-17 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_waterintake"),
        ("training", "0002_exercise_guide"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubstitutionSeance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "exercise_substitut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="substitutions",
                        to="training.exercise",
                        verbose_name="exercice de remplacement",
                    ),
                ),
                (
                    "workout_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions",
                        to="training.workoutexercise",
                        verbose_name="créneau remplacé",
                    ),
                ),
                (
                    "workout_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions",
                        to="tracking.workoutlog",
                        verbose_name="séance",
                    ),
                ),
            ],
            options={
                "verbose_name": "substitution de séance",
                "verbose_name_plural": "substitutions de séance",
                "ordering": ["-cree_le"],
                "unique_together": {("workout_log", "workout_exercise")},
            },
        ),
    ]
