# Generated by Django 6.0.5 on 2026-06-14 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=120, unique=True, verbose_name="nom"),
                ),
                (
                    "nom_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="nom (anglais)"
                    ),
                ),
                (
                    "groupe_musculaire",
                    models.CharField(
                        choices=[
                            ("pectoraux", "Pectoraux"),
                            ("dos", "Dos"),
                            ("jambes", "Jambes"),
                            ("epaules", "Épaules"),
                            ("biceps", "Biceps"),
                            ("triceps", "Triceps"),
                            ("abdos", "Abdos"),
                            ("mollets", "Mollets"),
                        ],
                        max_length=20,
                        verbose_name="groupe musculaire",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("compose", "Composé"), ("isolation", "Isolation")],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "materiel_requis",
                    models.CharField(
                        choices=[
                            ("salle_complete", "Salle complète"),
                            ("halteres_maison", "Haltères maison"),
                            ("poids_du_corps", "Poids du corps"),
                        ],
                        default="salle_complete",
                        max_length=20,
                        verbose_name="matériel requis",
                    ),
                ),
                (
                    "niveau_minimum",
                    models.CharField(
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                        ],
                        default="debutant",
                        max_length=20,
                        verbose_name="niveau minimum",
                    ),
                ),
                (
                    "description_technique",
                    models.TextField(blank=True, verbose_name="description technique"),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="URL vidéo")),
                (
                    "a_valider",
                    models.BooleanField(default=False, verbose_name="à valider"),
                ),
            ],
            options={
                "verbose_name": "exercice",
                "verbose_name_plural": "exercices",
                "ordering": ["groupe_musculaire", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "objectif",
                    models.CharField(
                        choices=[
                            ("prise_de_masse", "Prise de masse"),
                            ("seche", "Sèche"),
                            ("recomposition", "Recomposition"),
                            ("force", "Force"),
                            ("maintien", "Maintien"),
                        ],
                        max_length=20,
                        verbose_name="objectif",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="date de début")),
                (
                    "duree_semaines",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (4, "4 semaines"),
                            (8, "8 semaines"),
                            (12, "12 semaines"),
                        ],
                        default=8,
                        verbose_name="durée (semaines)",
                    ),
                ),
                (
                    "split",
                    models.CharField(
                        choices=[
                            ("full_body", "Full body"),
                            ("half_body", "Half body"),
                            ("push_pull_legs", "Push / Pull / Legs"),
                            ("split_classique", "Split classique"),
                        ],
                        max_length=20,
                        verbose_name="split",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "genere_par_ia",
                    models.BooleanField(default=False, verbose_name="généré par IA"),
                ),
                ("prompt_ia", models.TextField(blank=True, verbose_name="prompt IA")),
                (
                    "reponse_ia",
                    models.JSONField(blank=True, null=True, verbose_name="réponse IA"),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "programme",
                "verbose_name_plural": "programmes",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jour_numero",
                    models.PositiveSmallIntegerField(verbose_name="numéro de jour"),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="ex: Push — Pectoraux/Épaules/Triceps",
                        max_length=150,
                        verbose_name="nom",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_days",
                        to="training.program",
                        verbose_name="programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "journée d'entraînement",
                "verbose_name_plural": "journées d'entraînement",
                "ordering": ["program", "jour_numero"],
                "unique_together": {("program", "jour_numero")},
            },
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(default=1, verbose_name="ordre"),
                ),
                ("series", models.PositiveSmallIntegerField(verbose_name="séries")),
                (
                    "repetitions",
                    models.CharField(
                        help_text="ex: 8-12", max_length=20, verbose_name="répétitions"
                    ),
                ),
                (
                    "temps_repos_secondes",
                    models.PositiveSmallIntegerField(verbose_name="temps de repos (s)"),
                ),
                (
                    "tempo",
                    models.CharField(
                        blank=True,
                        help_text="ex: 2-0-2",
                        max_length=20,
                        verbose_name="tempo",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "progression_type",
                    models.CharField(
                        choices=[
                            ("double_progression", "Double progression"),
                            ("charge_lineaire", "Charge linéaire"),
                            ("rpe", "RPE"),
                        ],
                        default="double_progression",
                        max_length=20,
                        verbose_name="type de progression",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.exercise",
                        verbose_name="exercice",
                    ),
                ),
                (
                    "workout_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="training.workoutday",
                        verbose_name="journée",
                    ),
                ),
            ],
            options={
                "verbose_name": "exercice de séance",
                "verbose_name_plural": "exercices de séance",
                "ordering": ["workout_day", "ordre"],
            },
        ),
    ]
