# Generated by Django 6.0.5 on 2026-06-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="consignes_securite",
            field=models.TextField(
                blank=True,
                help_text="Points clés pour exécuter sans se blesser.",
                verbose_name="consignes de sécurité",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="erreurs_frequentes",
            field=models.TextField(
                blank=True,
                help_text="Erreurs typiques de débutant à éviter.",
                verbose_name="erreurs fréquentes",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="guide_a_valider",
            field=models.BooleanField(default=False, verbose_name="guide à valider"),
        ),
        migrations.AddField(
            model_name="exercise",
            name="muscles_secondaires",
            field=models.CharField(
                blank=True,
                help_text="Muscles assistants (texte libre, ex: triceps, deltoïde antérieur). Le groupe musculaire reste le muscle primaire.",
                max_length=255,
                verbose_name="muscles secondaires",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="description_technique",
            field=models.TextField(
                blank=True,
                help_text="Mise en place du corps et déroulé du mouvement.",
                verbose_name="positionnement & exécution",
            ),
        ),
    ]
